name: Secure Preferences Library
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup Dotnet
        uses: actions/checkout@v2
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
      - name: Build Secure Preferences Library
        run: dotnet build SecurePreferences/SecurePreferences.csproj
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout and Setup Dotnet
        uses: actions/checkout@v2
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
      - name: Run tests
        run: dotnet test SecurePreferences.Test/SecurePreferences.Test.csproj
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout and Setup Dotnet
        uses: actions/checkout@v2
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
      - name: Deploy Secure Preferences Library
        run: dotnet pack --configuration Release SecurePreferences/SecurePreferences.csproj
      - name: Publish Secure Preferences Library
        run: dotnet nuget push SecurePreferences/bin/Release/SecurePreferences.1.0.3.1.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json